### ISSUE TITLE
Failed to generate when changing player character

### ISSUE THREAD

**Issue by Supertailsfan** [IntelOrca/biorand#310]
### Version

3.0.1 (412b94e)

### Seed

R730-ZVE8-LTHHAHMZ9YE00NRPJV61V0XK1HH0ZZZZWJZ

### Scenario

RE 3 (Jill)

### What happened?

When trying to change to any character, no matter the seed, it always fails to generate. It works fine for RE 1 & 2

This is what the log says:

> BioRand 3.0.1 (412b94e)
    Seed: R730-ZVE8-1THHAHMZ9YC00NRPJV61V0XK1HH0ZZZZWJZ
    Player: 0 Jill
    Scenario: A
Randomizing Player:
    jill.re3 becomes kendo.re2r
    Exception: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
       at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.set_Item(Int32 index, T value)
   at IntelOrca.Biohazard.VabFile.SetSampleFromPCM(Int32 index, Byte[] data)
   at IntelOrca.Biohazard.RE3.Re3Randomiser.SwapPlayerCharacter(RandoConfig config, RandoLogger logger, String actor, FileRepository fileRepository)
   at IntelOrca.Biohazard.RE3.Re3Randomiser.ChangePlayerCharacters(RandoConfig config, RandoLogger logger, GameData gameData, FileRepository fileRepository)
   at IntelOrca.Biohazard.BaseRandomiser.GenerateRdts(RandoConfig config, IRandoProgress progress, FileRepository fileRepository)

[log_pl0.txt](https://github.com/IntelOrca/biorand/files/11006705/log_pl0.txt)

**Comment by IntelOrca** [comment]
It looks like your version of RE 3 is different to what biorand expects. Where did you get your version from, is it possible for me to get the same version?

**Comment by Supertailsfan** [comment]
Believe I got my version from the official RE speedrun discord. Which they had a link to a video about it. They use the Taiwan version. Although, when I got it, all three games shared the server. Then patched it with the sourcenext 1.1.0 patch to use the classic REbirth patch 

Here is the RE 3 speedrun server. But the original link I got it from was taken down
https://discord.gg/yM6pQMf

**Comment by IntelOrca** [comment]
Closing due to incompatible version
