### ISSUE TITLE
biorand failed to generate

### ISSUE THREAD

**Issue by wickedLC21** [IntelOrca/biorand#559]
### Version

3.1.1 (1e8850a)

### Seed

R730-M4RV-TWHH4HMZ9Y900Q1ZZZZZZZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### Player Character

Jill

### What happened?

I saw the issue in RE3 that Resident Evil 2 settings: "one or more of your room file did not match the original version."

Logs:
BioRand 3.1.1 (1e8850a)
    Seed: R730-M4RV-TWHH4HMZ9Y9R0Q1ZZZZZZZZZZZZZZZZZZZZZZZZZZZ
    Player: 0 Jill
    Scenario: A
Creating Original Room Graph:
    Exception: Object reference not set to an instance of an object.
       at IntelOrca.Biohazard.DoorRandomiser.GetOrCreateNode(RdtId rdtId)
   at IntelOrca.Biohazard.DoorRandomiser.CreateOriginalGraph()
   at IntelOrca.Biohazard.BaseRandomiser.GenerateRdts(RandoConfig config, IRandoProgress progress, FileRepository fileRepository)

**Comment by IntelOrca** [comment]
Caused by incompatible version of the game
