### ISSUE TITLE
RE1: Can not generate seed with checkmark on "Change Player Character"

### ISSUE THREAD

**Issue by tofubotu** [IntelOrca/biorand#616]
### Version

3.1.4 (25e489a)

### Seed

R710-QMX3-VWZE60M5J9Y200Q1VFCVHXZ1ZZZZZZZZZZZZZZZZZZZZZ

### Scenario

RE 1 (Chris)

### Player Character

Ark

### What happened?

If to remove Change Player character checkmark, the mod is generated. I tried using run as admin too. I tried another time after removing mod folder completely. Very odd.
![image](https://github.com/IntelOrca/biorand/assets/2536466/05a81a1a-23bd-48a6-9006-677c392d9ed3)

**Comment by tofubotu** [comment]
Log 

`    Randomizing room 306 with enemy: Tyrant
      Created 306:0 (0x0) [TYRANT 1,0,0,0,0] at (4558,0,3729)
      Created 306:1 (0x0) [TYRANT 1,0,0,0,0] at (7479,0,8453)
Randomizing Player:
    chris becomes ark
    Exception: Access to the path 'C:\Tofu_Temp\re1pc\mod_biorand\players\w00.emw' is denied.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at IntelOrca.Biohazard.BioRand.RE1.Re1Randomiser.SwapPlayerCharacter(RandoConfig config, RandoLogger logger, GameData gameData, Int32 pldIndex, String actor, FileRepository fileRepository)
   at IntelOrca.Biohazard.BioRand.RE1.Re1Randomiser.ChangePlayerCharacters(RandoConfig config, RandoLogger logger, GameData gameData, FileRepository fileRepository)
   at IntelOrca.Biohazard.BioRand.BaseRandomiser.GenerateRdts(RandoConfig config, IRandoProgress progress, FileRepository fileRepository)`

**Comment by tofubotu** [comment]
Something happened with Filesystem, after following commands, all ok again
takeown /a /r /d Y /f C:\Tofu_Temp
icacls C:\Tofu_Temp /grant administrators:F /t
